FROM centos:7

ENV PACKAGES="jq git"
ENV BATS_VERSION="v0.4.0"

RUN yum install -y epel-release && \
    yum install -y $PACKAGES && \
    rpm -q --queryformat "" $PACKAGES

RUN git clone https://github.com/sstephenson/bats.git && \
    git --git-dir=bats/.git checkout -b $BATS_VERSION $BATS_VERSION >/dev/null && \
    bats/install.sh /usr/local

COPY . /cico
WORKDIR /cico

COPY ./scripts/env-toolkit /usr/local/bin

CMD ["bats", "tests/env-toolkit.bats"]
